name: Sturgeon Projects
favicon: null
layout_spectrum: 0.7220948808826506
typography_spectrum: 0.8754092291928828
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7894a9'
    - '#aad3e7'
    - '#27475e'
    - '#ffffff'
    - '#010000'
  brandStrength: 0.32575628929771483
  lightness: 0.575687607517466
  saturation: 0.5571439885534346
  rhythmicContrast: 0.5770196369849145
purpose: []
